# Generated by Django 2.2.1 on 2020-01-29 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("currency_rates", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="currency_bought",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_rates",
                to="currency_rates.Currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="currency_sold",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selling_rates",
                to="currency_rates.Currency",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("currency_sold", "currency_bought", "date")},
        ),
        migrations.RemoveField(model_name="exchangerate", name="currency"),
    ]
